openapi: 3.2.0
info:
  title: Greenly Carbon Analytics Live API
  version: '1.5'
  description: '# Introduction

    The Greenly Carbon Analytics API is a set of RESTful services which enable the enrichment of bank transactions with carbon footprint analytics.'
  contact:
    email: contact@greenly.earth
servers:
- url: https://api.greenly.earth/v1.5
tags:
- name: Live
paths:
  /live:
    get:
      operationId: IsLive
      responses:
        '204':
          description: No content
        '401':
          description: Authentication Failed
        '503':
          description: Down
      tags:
      - Live
      security: []
      parameters: []
      summary: Is live
      x-summary-source: derived
components:
  securitySchemes:
    api_key:
      type: apiKey
      name: api-key
      in: header
